# Generated by Django 2.0.5 on 2018-05-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_auto_20180514_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('background', models.CharField(max_length=60)),
                ('frame', models.CharField(max_length=60)),
                ('border', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('accent', models.CharField(max_length=60)),
            ],
        ),
    ]
