# Generated by Django 2.0.5 on 2018-05-19 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_scheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='board',
            name='genesis',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 19, 17, 19, 52, 992491)),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
