# Generated by Django 2.0.5 on 2018-05-19 22:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0004_auto_20180519_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='whiteboard.Scheme'),
        ),
        migrations.AlterField(
            model_name='board',
            name='genesis',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 19, 17, 28, 56, 903970)),
        ),
    ]
